<a href="https://colab.research.google.com/github/Roystan-Dsouza/dlithe-internship/blob/master/Dlithe_Class3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import random

print("Number Guessing is a game")
### this variable is tracking chances
chances = 0

number = random.randint(1, 9)

print("Please guess a number between 1 and 9")

while chances < 5 :
  guess = int(input("Enter a number"))

  if guess == number :
    print("Congrats you have won!")
    break

  elif guess < number :
    print("Your guess is a bit low")

  else : 
    print("Your guess is too high")

  chances+=1

if not chances < 5 :
  print("You lost as the betting number is", number)

Number Guessing is a game
Please guess a number between 1 and 9
Enter a number5
Your guess is too high
Enter a number2
Your guess is a bit low
Enter a number3
Your guess is a bit low
Enter a number4
Congrats you have won!


In [ ]:
import numpy as np

In [ ]:
my_list = [1, 2, 3]

np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(2)

array([0.34522959, 0.88303494])

In [ ]:
np.random.rand(5,5)

array([[0.46498123, 0.04574143, 0.1018778 , 0.69763345, 0.79161639],
       [0.43522141, 0.70460824, 0.70880487, 0.91024118, 0.18321324],
       [0.08026531, 0.51050664, 0.1124034 , 0.10554858, 0.31245667],
       [0.86538539, 0.08404752, 0.33682924, 0.30269272, 0.78165085],
       [0.66403167, 0.35633905, 0.02738674, 0.36109644, 0.32712998]])

In [ ]:
np.random.randn(5, 5)

array([[ 1.32096332,  1.25158291,  0.37536728, -1.11292836, -1.01627779],
       [-0.43427047,  0.24307416,  1.34934658,  0.34067266,  0.81971751],
       [ 0.31033399, -1.18279471,  0.53132006, -0.97870955,  0.79677372],
       [-1.04735148, -2.04411757, -1.19241324,  0.2531064 ,  0.11599107],
       [ 1.56264695, -1.4188063 ,  1.059305  ,  0.20089482, -1.15669676]])

In [ ]:
np.random.randint(10)

2

In [ ]:
np.random.randint(1, 100, 10)

array([59,  5,  7, 79,  5, 75, 45, 22, 62, 41])

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0, 50, 10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([22, 21, 34, 27, 18, 39, 43,  2,  5, 36])

In [ ]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr.max()

43

In [ ]:
ranarr.argmax()

6

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.argmin()

7

In [ ]:
arr.shape

(25,)

In [ ]:
arr.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1, 25).shape

(1, 25)

In [ ]:
arr.reshape(25, 1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
import numpy as np
arr = np.arange(0, 10)

In [ ]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
arr/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
1/arr

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

9

In [ ]:
np.max(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[7]

7

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[0:5] = 100

In [ ]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [ ]:
slice_of_arr[:] = 99

In [ ]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [ ]:
arr_2d = np.array(([5, 10, 12], [1, 2, 3], [5, 6, 7]))

In [ ]:
arr_2d

array([[ 5, 10, 12],
       [ 1,  2,  3],
       [ 5,  6,  7]])

In [ ]:
arr_2d[1]

array([1, 2, 3])

In [ ]:
arr_2d[1][0]

1

In [ ]:
arr_2d[:2][1:]

array([[1, 2, 3]])

In [ ]:
arr_2d[2]

array([5, 6, 7])

In [ ]:
import numpy as np
arr2d = np.zeros((10, 10))

arr_length = arr2d.shape[1]

for i in range(arr_length) :
  arr2d[i] = i

In [ ]:
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
arr2d[[6, 4, 2, 5]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [ ]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])